// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: fsServer.proto

package fileSystemServer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListaArquivosParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListaArquivosParam) Reset() {
	*x = ListaArquivosParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fsServer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListaArquivosParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaArquivosParam) ProtoMessage() {}

func (x *ListaArquivosParam) ProtoReflect() protoreflect.Message {
	mi := &file_fsServer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaArquivosParam.ProtoReflect.Descriptor instead.
func (*ListaArquivosParam) Descriptor() ([]byte, []int) {
	return file_fsServer_proto_rawDescGZIP(), []int{0}
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fsServer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_fsServer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_fsServer_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Bloco struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockInfo *BlocoMetadata `protobuf:"bytes,1,opt,name=block_info,json=blockInfo,proto3" json:"block_info,omitempty"`
	Content   []byte         `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Bloco) Reset() {
	*x = Bloco{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fsServer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bloco) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bloco) ProtoMessage() {}

func (x *Bloco) ProtoReflect() protoreflect.Message {
	mi := &file_fsServer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bloco.ProtoReflect.Descriptor instead.
func (*Bloco) Descriptor() ([]byte, []int) {
	return file_fsServer_proto_rawDescGZIP(), []int{2}
}

func (x *Bloco) GetBlockInfo() *BlocoMetadata {
	if x != nil {
		return x.BlockInfo
	}
	return nil
}

func (x *Bloco) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ArquivoMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size       int64  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	BlockIndex int32  `protobuf:"varint,3,opt,name=block_index,json=blockIndex,proto3" json:"block_index,omitempty"`
}

func (x *ArquivoMetadata) Reset() {
	*x = ArquivoMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fsServer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArquivoMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArquivoMetadata) ProtoMessage() {}

func (x *ArquivoMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_fsServer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArquivoMetadata.ProtoReflect.Descriptor instead.
func (*ArquivoMetadata) Descriptor() ([]byte, []int) {
	return file_fsServer_proto_rawDescGZIP(), []int{3}
}

func (x *ArquivoMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArquivoMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ArquivoMetadata) GetBlockIndex() int32 {
	if x != nil {
		return x.BlockIndex
	}
	return 0
}

type BlocoMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index     int32  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	BlockSize int32  `protobuf:"varint,2,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	FileName  string `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *BlocoMetadata) Reset() {
	*x = BlocoMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fsServer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlocoMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlocoMetadata) ProtoMessage() {}

func (x *BlocoMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_fsServer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlocoMetadata.ProtoReflect.Descriptor instead.
func (*BlocoMetadata) Descriptor() ([]byte, []int) {
	return file_fsServer_proto_rawDescGZIP(), []int{4}
}

func (x *BlocoMetadata) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BlocoMetadata) GetBlockSize() int32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *BlocoMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type DadosNoInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *DadosNoInfo) Reset() {
	*x = DadosNoInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fsServer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DadosNoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DadosNoInfo) ProtoMessage() {}

func (x *DadosNoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fsServer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DadosNoInfo.ProtoReflect.Descriptor instead.
func (*DadosNoInfo) Descriptor() ([]byte, []int) {
	return file_fsServer_proto_rawDescGZIP(), []int{5}
}

func (x *DadosNoInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DadosNoInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type PrincipalNoInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *PrincipalNoInfo) Reset() {
	*x = PrincipalNoInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fsServer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrincipalNoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalNoInfo) ProtoMessage() {}

func (x *PrincipalNoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fsServer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalNoInfo.ProtoReflect.Descriptor instead.
func (*PrincipalNoInfo) Descriptor() ([]byte, []int) {
	return file_fsServer_proto_rawDescGZIP(), []int{6}
}

func (x *PrincipalNoInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PrincipalNoInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ServidoresDados struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServidoresDados []*DadosNoInfo `protobuf:"bytes,1,rep,name=servidores_dados,json=servidoresDados,proto3" json:"servidores_dados,omitempty"`
}

func (x *ServidoresDados) Reset() {
	*x = ServidoresDados{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fsServer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServidoresDados) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServidoresDados) ProtoMessage() {}

func (x *ServidoresDados) ProtoReflect() protoreflect.Message {
	mi := &file_fsServer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServidoresDados.ProtoReflect.Descriptor instead.
func (*ServidoresDados) Descriptor() ([]byte, []int) {
	return file_fsServer_proto_rawDescGZIP(), []int{7}
}

func (x *ServidoresDados) GetServidoresDados() []*DadosNoInfo {
	if x != nil {
		return x.ServidoresDados
	}
	return nil
}

type LocalizacaoBloco struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataNodeInfo *DadosNoInfo   `protobuf:"bytes,1,opt,name=data_node_info,json=dataNodeInfo,proto3" json:"data_node_info,omitempty"`
	BlockInfo    *BlocoMetadata `protobuf:"bytes,2,opt,name=block_info,json=blockInfo,proto3" json:"block_info,omitempty"`
}

func (x *LocalizacaoBloco) Reset() {
	*x = LocalizacaoBloco{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fsServer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalizacaoBloco) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalizacaoBloco) ProtoMessage() {}

func (x *LocalizacaoBloco) ProtoReflect() protoreflect.Message {
	mi := &file_fsServer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalizacaoBloco.ProtoReflect.Descriptor instead.
func (*LocalizacaoBloco) Descriptor() ([]byte, []int) {
	return file_fsServer_proto_rawDescGZIP(), []int{8}
}

func (x *LocalizacaoBloco) GetDataNodeInfo() *DadosNoInfo {
	if x != nil {
		return x.DataNodeInfo
	}
	return nil
}

func (x *LocalizacaoBloco) GetBlockInfo() *BlocoMetadata {
	if x != nil {
		return x.BlockInfo
	}
	return nil
}

type MapeamentoLocalizacaoBloco struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mapping  []*LocalizacaoBloco `protobuf:"bytes,1,rep,name=mapping,proto3" json:"mapping,omitempty"`
	FileInfo *ArquivoMetadata    `protobuf:"bytes,2,opt,name=file_info,json=fileInfo,proto3" json:"file_info,omitempty"`
}

func (x *MapeamentoLocalizacaoBloco) Reset() {
	*x = MapeamentoLocalizacaoBloco{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fsServer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapeamentoLocalizacaoBloco) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapeamentoLocalizacaoBloco) ProtoMessage() {}

func (x *MapeamentoLocalizacaoBloco) ProtoReflect() protoreflect.Message {
	mi := &file_fsServer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapeamentoLocalizacaoBloco.ProtoReflect.Descriptor instead.
func (*MapeamentoLocalizacaoBloco) Descriptor() ([]byte, []int) {
	return file_fsServer_proto_rawDescGZIP(), []int{9}
}

func (x *MapeamentoLocalizacaoBloco) GetMapping() []*LocalizacaoBloco {
	if x != nil {
		return x.Mapping
	}
	return nil
}

func (x *MapeamentoLocalizacaoBloco) GetFileInfo() *ArquivoMetadata {
	if x != nil {
		return x.FileInfo
	}
	return nil
}

type RelatorioBloco struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataNodeInfo *DadosNoInfo     `protobuf:"bytes,1,opt,name=data_node_info,json=dataNodeInfo,proto3" json:"data_node_info,omitempty"`
	Blocks       []*BlocoMetadata `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
}

func (x *RelatorioBloco) Reset() {
	*x = RelatorioBloco{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fsServer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelatorioBloco) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatorioBloco) ProtoMessage() {}

func (x *RelatorioBloco) ProtoReflect() protoreflect.Message {
	mi := &file_fsServer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatorioBloco.ProtoReflect.Descriptor instead.
func (*RelatorioBloco) Descriptor() ([]byte, []int) {
	return file_fsServer_proto_rawDescGZIP(), []int{10}
}

func (x *RelatorioBloco) GetDataNodeInfo() *DadosNoInfo {
	if x != nil {
		return x.DataNodeInfo
	}
	return nil
}

func (x *RelatorioBloco) GetBlocks() []*BlocoMetadata {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type ListaArquivos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []*ArquivoMetadata `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *ListaArquivos) Reset() {
	*x = ListaArquivos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fsServer_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListaArquivos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaArquivos) ProtoMessage() {}

func (x *ListaArquivos) ProtoReflect() protoreflect.Message {
	mi := &file_fsServer_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaArquivos.ProtoReflect.Descriptor instead.
func (*ListaArquivos) Descriptor() ([]byte, []int) {
	return file_fsServer_proto_rawDescGZIP(), []int{11}
}

func (x *ListaArquivos) GetFiles() []*ArquivoMetadata {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_fsServer_proto protoreflect.FileDescriptor

var file_fsServer_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x66, 0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x41, 0x72, 0x71, 0x75, 0x69, 0x76, 0x6f,
	0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x22, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x50, 0x0a, 0x05, 0x42, 0x6c,
	0x6f, 0x63, 0x6f, 0x12, 0x2d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6f, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x5a, 0x0a, 0x0f,
	0x41, 0x72, 0x71, 0x75, 0x69, 0x76, 0x6f, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x61, 0x0a, 0x0d, 0x42, 0x6c, 0x6f, 0x63,
	0x6f, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x0b, 0x44,
	0x61, 0x64, 0x6f, 0x73, 0x4e, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x35,
	0x0a, 0x0f, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x4e, 0x6f, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x4a, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f,
	0x72, 0x65, 0x73, 0x44, 0x61, 0x64, 0x6f, 0x73, 0x12, 0x37, 0x0a, 0x10, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x64, 0x6f, 0x72, 0x65, 0x73, 0x5f, 0x64, 0x61, 0x64, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x44, 0x61, 0x64, 0x6f, 0x73, 0x4e, 0x6f, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x65, 0x73, 0x44, 0x61, 0x64, 0x6f,
	0x73, 0x22, 0x75, 0x0a, 0x10, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x63, 0x61, 0x6f,
	0x42, 0x6c, 0x6f, 0x63, 0x6f, 0x12, 0x32, 0x0a, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x44, 0x61, 0x64, 0x6f, 0x73, 0x4e, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x64, 0x61, 0x74,
	0x61, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x42, 0x6c, 0x6f, 0x63, 0x6f, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x09, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x78, 0x0a, 0x1a, 0x4d, 0x61, 0x70, 0x65,
	0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x63, 0x61,
	0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6f, 0x12, 0x2b, 0x0a, 0x07, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x69,
	0x7a, 0x61, 0x63, 0x61, 0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6f, 0x52, 0x07, 0x6d, 0x61, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x12, 0x2d, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x41, 0x72, 0x71, 0x75, 0x69, 0x76, 0x6f,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x6c, 0x0a, 0x0e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x69, 0x6f, 0x42,
	0x6c, 0x6f, 0x63, 0x6f, 0x12, 0x32, 0x0a, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x44,
	0x61, 0x64, 0x6f, 0x73, 0x4e, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x64, 0x61, 0x74, 0x61,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6f,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73,
	0x22, 0x37, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x41, 0x72, 0x71, 0x75, 0x69, 0x76, 0x6f,
	0x73, 0x12, 0x26, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x41, 0x72, 0x71, 0x75, 0x69, 0x76, 0x6f, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x32, 0xc8, 0x02, 0x0a, 0x0b, 0x50, 0x72,
	0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x4e, 0x6f, 0x12, 0x27, 0x0a, 0x09, 0x65, 0x73, 0x74,
	0x61, 0x41, 0x74, 0x69, 0x76, 0x6f, 0x12, 0x0f, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x69, 0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6f, 0x1a, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x00, 0x12, 0x41, 0x0a, 0x0e, 0x61, 0x74, 0x72, 0x69, 0x62, 0x75, 0x69, 0x72, 0x42, 0x6c,
	0x6f, 0x63, 0x6f, 0x73, 0x12, 0x10, 0x2e, 0x41, 0x72, 0x71, 0x75, 0x69, 0x76, 0x6f, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x1b, 0x2e, 0x4d, 0x61, 0x70, 0x65, 0x61, 0x6d, 0x65,
	0x6e, 0x74, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x63, 0x61, 0x6f, 0x42, 0x6c,
	0x6f, 0x63, 0x6f, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x16, 0x6f, 0x62, 0x74, 0x65, 0x72, 0x4c, 0x6f,
	0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x63, 0x6f, 0x65, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6f, 0x12,
	0x10, 0x2e, 0x41, 0x72, 0x71, 0x75, 0x69, 0x76, 0x6f, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0x1b, 0x2e, 0x4d, 0x61, 0x70, 0x65, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x4c, 0x6f,
	0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x63, 0x61, 0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6f, 0x22, 0x00,
	0x12, 0x36, 0x0a, 0x0d, 0x6c, 0x69, 0x73, 0x74, 0x61, 0x41, 0x72, 0x71, 0x75, 0x69, 0x76, 0x6f,
	0x73, 0x12, 0x13, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x41, 0x72, 0x71, 0x75, 0x69, 0x76, 0x6f,
	0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x0e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x41, 0x72,
	0x71, 0x75, 0x69, 0x76, 0x6f, 0x73, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x0a, 0x61, 0x64, 0x63, 0x4e,
	0x6f, 0x44, 0x61, 0x64, 0x6f, 0x73, 0x12, 0x0c, 0x2e, 0x44, 0x61, 0x64, 0x6f, 0x73, 0x4e, 0x6f,
	0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12,
	0x23, 0x0a, 0x0e, 0x61, 0x64, 0x63, 0x4e, 0x6f, 0x76, 0x6f, 0x41, 0x72, 0x71, 0x75, 0x69, 0x76,
	0x6f, 0x12, 0x06, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6f, 0x1a, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x00, 0x32, 0x8f, 0x01, 0x0a, 0x07, 0x44, 0x61, 0x64, 0x6f, 0x73, 0x4e, 0x6f,
	0x12, 0x24, 0x0a, 0x08, 0x6c, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6f, 0x12, 0x0e, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6f, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x06, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6f, 0x22, 0x00, 0x12, 0x22, 0x0a, 0x0d, 0x65, 0x73, 0x63, 0x72, 0x65, 0x76,
	0x65, 0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6f, 0x12, 0x06, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6f, 0x1a,
	0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x11, 0x6c, 0x69,
	0x73, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x41, 0x72, 0x71, 0x75, 0x69, 0x76, 0x6f, 0x73, 0x12,
	0x13, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x41, 0x72, 0x71, 0x75, 0x69, 0x76, 0x6f, 0x73, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x1a, 0x0e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x41, 0x72, 0x71, 0x75,
	0x69, 0x76, 0x6f, 0x73, 0x22, 0x00, 0x42, 0x23, 0x5a, 0x21, 0x6d, 0x76, 0x72, 0x70, 0x6c, 0x2e,
	0x64, 0x65, 0x76, 0x2f, 0x64, 0x66, 0x73, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_fsServer_proto_rawDescOnce sync.Once
	file_fsServer_proto_rawDescData = file_fsServer_proto_rawDesc
)

func file_fsServer_proto_rawDescGZIP() []byte {
	file_fsServer_proto_rawDescOnce.Do(func() {
		file_fsServer_proto_rawDescData = protoimpl.X.CompressGZIP(file_fsServer_proto_rawDescData)
	})
	return file_fsServer_proto_rawDescData
}

var file_fsServer_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_fsServer_proto_goTypes = []interface{}{
	(*ListaArquivosParam)(nil),         // 0: ListaArquivosParam
	(*Status)(nil),                     // 1: Status
	(*Bloco)(nil),                      // 2: Bloco
	(*ArquivoMetadata)(nil),            // 3: ArquivoMetadata
	(*BlocoMetadata)(nil),              // 4: BlocoMetadata
	(*DadosNoInfo)(nil),                // 5: DadosNoInfo
	(*PrincipalNoInfo)(nil),            // 6: PrincipalNoInfo
	(*ServidoresDados)(nil),            // 7: ServidoresDados
	(*LocalizacaoBloco)(nil),           // 8: LocalizacaoBloco
	(*MapeamentoLocalizacaoBloco)(nil), // 9: MapeamentoLocalizacaoBloco
	(*RelatorioBloco)(nil),             // 10: RelatorioBloco
	(*ListaArquivos)(nil),              // 11: ListaArquivos
}
var file_fsServer_proto_depIdxs = []int32{
	4,  // 0: Bloco.block_info:type_name -> BlocoMetadata
	5,  // 1: ServidoresDados.servidores_dados:type_name -> DadosNoInfo
	5,  // 2: LocalizacaoBloco.data_node_info:type_name -> DadosNoInfo
	4,  // 3: LocalizacaoBloco.block_info:type_name -> BlocoMetadata
	8,  // 4: MapeamentoLocalizacaoBloco.mapping:type_name -> LocalizacaoBloco
	3,  // 5: MapeamentoLocalizacaoBloco.file_info:type_name -> ArquivoMetadata
	5,  // 6: RelatorioBloco.data_node_info:type_name -> DadosNoInfo
	4,  // 7: RelatorioBloco.blocks:type_name -> BlocoMetadata
	3,  // 8: ListaArquivos.files:type_name -> ArquivoMetadata
	10, // 9: PrincipalNo.estaAtivo:input_type -> RelatorioBloco
	3,  // 10: PrincipalNo.atribuirBlocos:input_type -> ArquivoMetadata
	3,  // 11: PrincipalNo.obterLocalizacoesBloco:input_type -> ArquivoMetadata
	0,  // 12: PrincipalNo.listaArquivos:input_type -> ListaArquivosParam
	5,  // 13: PrincipalNo.adcNoDados:input_type -> DadosNoInfo
	2,  // 14: PrincipalNo.adcNovoArquivo:input_type -> Bloco
	4,  // 15: DadosNo.lerBloco:input_type -> BlocoMetadata
	2,  // 16: DadosNo.escreverBloco:input_type -> Bloco
	0,  // 17: DadosNo.listaDataArquivos:input_type -> ListaArquivosParam
	1,  // 18: PrincipalNo.estaAtivo:output_type -> Status
	9,  // 19: PrincipalNo.atribuirBlocos:output_type -> MapeamentoLocalizacaoBloco
	9,  // 20: PrincipalNo.obterLocalizacoesBloco:output_type -> MapeamentoLocalizacaoBloco
	11, // 21: PrincipalNo.listaArquivos:output_type -> ListaArquivos
	1,  // 22: PrincipalNo.adcNoDados:output_type -> Status
	1,  // 23: PrincipalNo.adcNovoArquivo:output_type -> Status
	2,  // 24: DadosNo.lerBloco:output_type -> Bloco
	1,  // 25: DadosNo.escreverBloco:output_type -> Status
	11, // 26: DadosNo.listaDataArquivos:output_type -> ListaArquivos
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_fsServer_proto_init() }
func file_fsServer_proto_init() {
	if File_fsServer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fsServer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListaArquivosParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fsServer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fsServer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bloco); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fsServer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArquivoMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fsServer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlocoMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fsServer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DadosNoInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fsServer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrincipalNoInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fsServer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServidoresDados); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fsServer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalizacaoBloco); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fsServer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapeamentoLocalizacaoBloco); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fsServer_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelatorioBloco); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fsServer_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListaArquivos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fsServer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_fsServer_proto_goTypes,
		DependencyIndexes: file_fsServer_proto_depIdxs,
		MessageInfos:      file_fsServer_proto_msgTypes,
	}.Build()
	File_fsServer_proto = out.File
	file_fsServer_proto_rawDesc = nil
	file_fsServer_proto_goTypes = nil
	file_fsServer_proto_depIdxs = nil
}
